USE master;
GO

IF EXISTS(SELECT * FROM sys.databases WHERE name='ChatAppDB')
	DROP DATABASE ChatAppDB

SET DATEFORMAT YMD

CREATE DATABASE ChatAppDB;
GO

USE ChatAppDB;
GO

CREATE TABLE Users (
	UserID INT NOT NULL PRIMARY KEY,
	Name VARCHAR(255)
);

CREATE TABLE Chats (
	ChatID INT NOT NULL PRIMARY KEY
);

CREATE TABLE UsersInChats (
	UserID INT NOT NULL FOREIGN KEY(UserID) REFERENCES Users(UserID),
	ChatID INT NOT NULL FOREIGN KEY(ChatID) REFERENCES Chats(ChatID),
	CONSTRAINT PK_UsersInChats PRIMARY KEY (UserID, ChatID)
);

CREATE TABLE Messages (
	MessageID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ChatID INT FOREIGN KEY(ChatID) REFERENCES Chats(ChatID),
	AuthorID INT FOREIGN KEY(AuthorID) REFERENCES Users(UserID),
	Date VARCHAR(255),
	Text VARCHAR(255),
);

DELETE FROM Users
DELETE FROM Chats
DELETE FROM Messages
DELETE FROM UsersInChats

SELECT * FROM Messages M JOIN Users U ON U.UserID = M.AuthorID